# Generated by Django 5.2.4 on 2025-07-13 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("name", models.CharField(max_length=30, verbose_name="Country Name")),
                (
                    "abbreviation",
                    models.CharField(max_length=3, verbose_name="Abbreviation"),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="country_customuser_lastuser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FederativeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "name",
                    models.CharField(
                        max_length=30, verbose_name="Federative Unit Name"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=2, verbose_name="Abbreviation"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="federativeunit_country_country",
                        to="address.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="federativeunit_customuser_lastuser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federative Unit",
                "verbose_name_plural": "Federative Units",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("name", models.CharField(max_length=30, verbose_name="City Name")),
                (
                    "last_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="city_customuser_lastuser",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last User",
                    ),
                ),
                (
                    "federative_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="city_federativeunit_federativeunit",
                        to="address.federativeunit",
                        verbose_name="Federative Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["name"], name="idx_name_country"),
        ),
        migrations.AddIndex(
            model_name="federativeunit",
            index=models.Index(fields=["name"], name="idx_name_federative_unit"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["name"], name="idx_name_city"),
        ),
    ]
