# Generated by Django 5.2.4 on 2025-07-12 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sport",
                        max_length=100,
                        verbose_name="Sport Name",
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified this sport",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_sport",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sport",
                "verbose_name_plural": "Sports",
                "ordering": ["-id"],
            },
        ),
    ]
