# Generated by Django 5.2.4 on 2025-08-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteSport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "last_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Iniciante"),
                            ("INTERMEDIATE", "Intermediário"),
                            ("ADVANCED", "Avançado"),
                        ],
                        default="BEGINNER",
                        max_length=12,
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        db_column="sport_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sports.sports",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite_sports",
                "unique_together": {("user", "sport")},
            },
        ),
    ]
